language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  global:
    - DATEUTIL=python-dateutil==2.1
  matrix:
    - DJANGO=Django==1.3.7
    - DJANGO=Django==1.4.8
    - DJANGO=Django==1.5.4
    - DJANGO=https://github.com/django/django/tarball/stable/1.6.x DATEUTIL=python-dateutil==2.2

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=Django==1.3.7
    - python: 3.2
      env: DJANGO=Django==1.4.8
    - python: 3.3
      env: DJANGO=Django==1.3.7
    - python: 3.3
      env: DJANGO=Django==1.4.8

# command to install dependencies
install:
  - "pip install $DJANGO --use-mirrors"
  - "pip install . --use-mirrors"
  - "pip install -r tests/test_requirements.txt --use-mirrors"
# command to run tests
script: tests/runtests.py --with-pep8
